export const SWISS_CANTONS = [
  { code: 'AG', name: 'Aargau', region: 'de' },
  { code: 'AI', name: 'Appenzell Innerrhoden', region: 'de' },
  { code: 'AR', name: 'Appenzell Ausserrhoden', region: 'de' },
  { code: 'BE', name: 'Bern', region: 'de' },
  { code: 'BL', name: 'Basel-Landschaft', region: 'de' },
  { code: 'BS', name: 'Basel-Stadt', region: 'de' },
  { code: 'FR', name: 'Fribourg', region: 'mixed' },
  { code: 'GE', name: 'Geneve', region: 'fr' },
  { code: 'GL', name: 'Glarus', region: 'de' },
  { code: 'GR', name: 'Graubuenden', region: 'mixed' },
  { code: 'JU', name: 'Jura', region: 'fr' },
  { code: 'LU', name: 'Luzern', region: 'de' },
  { code: 'NE', name: 'Neuchatel', region: 'fr' },
  { code: 'NW', name: 'Nidwalden', region: 'de' },
  { code: 'OW', name: 'Obwalden', region: 'de' },
  { code: 'SG', name: 'St. Gallen', region: 'de' },
  { code: 'SH', name: 'Schaffhausen', region: 'de' },
  { code: 'SO', name: 'Solothurn', region: 'de' },
  { code: 'SZ', name: 'Schwyz', region: 'de' },
  { code: 'TG', name: 'Thurgau', region: 'de' },
  { code: 'TI', name: 'Ticino', region: 'it' },
  { code: 'UR', name: 'Uri', region: 'de' },
  { code: 'VD', name: 'Vaud', region: 'fr' },
  { code: 'VS', name: 'Valais', region: 'mixed' },
  { code: 'ZG', name: 'Zug', region: 'de' },
  { code: 'ZH', name: 'Zuerich', region: 'de' },
] as const;

export type CantonCode = (typeof SWISS_CANTONS)[number]['code'];

/** Neighboring cantons for location-based matching */
export const CANTON_NEIGHBORS: Record<string, string[]> = {
  ZH: ['AG', 'SH', 'TG', 'SG', 'SZ', 'ZG'],
  BE: ['SO', 'JU', 'NE', 'FR', 'VS', 'LU', 'OW', 'NW'],
  BS: ['BL', 'AG', 'SO'],
  BL: ['BS', 'AG', 'SO', 'JU'],
  AG: ['ZH', 'BL', 'BS', 'SO', 'LU', 'ZG'],
  LU: ['AG', 'ZG', 'SZ', 'NW', 'OW', 'BE'],
  SG: ['ZH', 'TG', 'AR', 'AI', 'GR', 'GL', 'SZ'],
  GR: ['SG', 'GL', 'UR', 'TI'],
  TI: ['GR', 'VS', 'UR'],
  VD: ['GE', 'FR', 'NE', 'VS'],
  GE: ['VD'],
  FR: ['BE', 'VD', 'NE'],
  SO: ['BE', 'AG', 'BL', 'BS', 'JU'],
  TG: ['ZH', 'SH', 'SG'],
  SH: ['ZH', 'TG'],
  SZ: ['ZH', 'ZG', 'LU', 'UR', 'GL', 'SG'],
  ZG: ['ZH', 'AG', 'LU', 'SZ'],
  NW: ['LU', 'OW', 'UR', 'BE'],
  OW: ['LU', 'NW', 'BE', 'UR'],
  UR: ['SZ', 'NW', 'OW', 'GR', 'TI'],
  GL: ['SZ', 'SG', 'GR'],
  AR: ['SG', 'AI'],
  AI: ['SG', 'AR'],
  JU: ['BL', 'SO', 'BE'],
  NE: ['FR', 'BE', 'VD'],
  VS: ['BE', 'VD', 'TI'],
};
