-- ============================================================
-- SEED DATA: Complete Swiss apprenticeship occupations (Berufe)
-- Source: berufsberatung.ch official list — 186 EFZ + 61 EBA
-- ============================================================

INSERT INTO berufe (code, name_de, field, education_type, description_de, personality_fit, duration_years, bb_id) VALUES

-- ═══════════════════════════════════════════════════════════════
-- EFZ PROFESSIONS (186)
-- ═══════════════════════════════════════════════════════════════

-- BAU / CONSTRUCTION
('33200', 'Maurer/in EFZ', 'Bau', 'EFZ', 'Maurer/innen errichten Mauerwerk, betonieren und verputzen Wände.', '{"realistic": 0.9, "investigative": 0.2, "artistic": 0.1, "social": 0.3, "enterprising": 0.2, "conventional": 0.3}', 3, '2931'),
('34500', 'Zeichner/in EFZ', 'Planung/Konstruktion', 'EFZ', 'Zeichner/innen erstellen Pläne für Architektur- und Bauprojekte mit CAD-Software.', '{"realistic": 0.4, "investigative": 0.5, "artistic": 0.7, "social": 0.2, "enterprising": 0.2, "conventional": 0.6}', 4, '7789'),
('ABD01', 'Abdichter/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '9946'),
('ANL01', 'Anlagen- und Apparatebauer/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3055'),
('ANF01', 'Anlagenführer/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 3, '7670'),
('APG01', 'Apparateglasbläser/in EFZ', 'Chemie/Physik', 'EFZ', NULL, '{}', 3, '10962'),
('ARM01', 'Architekturmodellbauer/in EFZ', 'Planung/Konstruktion', 'EFZ', NULL, '{}', 4, '2906'),
('AUO01', 'Augenoptiker/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 4, '3246'),
('47600', 'Automatiker/in EFZ', 'Elektrotechnik', 'EFZ', 'Automatiker/innen entwickeln und bauen automatisierte Steuerungen und Anlagen.', '{"realistic": 0.7, "investigative": 0.8, "artistic": 0.1, "social": 0.2, "enterprising": 0.2, "conventional": 0.5}', 4, '3794'),
('ATM01', 'Automatikmonteur/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 3, '3837'),
('AFF01', 'Automobil-Fachmann/-frau EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 3, '2970'),
('AME01', 'Automobil-Mechatroniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '2971'),
('21104', 'Bäcker/in-Konditor/in-Confiseur/in EFZ', 'Nahrung', 'EFZ', 'Bäcker/innen-Konditor/innen stellen Brot, Gebäck, Torten und Confiserie-Produkte her.', '{"realistic": 0.8, "investigative": 0.2, "artistic": 0.6, "social": 0.3, "enterprising": 0.3, "conventional": 0.4}', 3, '2956'),
('BMM01', 'Baumaschinenmechaniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '3035'),
('BWT01', 'Bauwerktrenner/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '3799'),
('BKG01', 'Bekleidungsgestalter/in EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '2939'),
('BTW01', 'Betonwerker/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '3760'),
('BDT01', 'Bindetechnologe/-login EFZ', 'Druck', 'EFZ', NULL, '{}', 4, '6689'),
('BLI01', 'Blasinstrumentenbauer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11227'),
('BPL01', 'Boden-Parkettleger/in EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 3, '3635'),
('BOO01', 'Bootbauer/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '3051'),
('BOF01', 'Bootfachwart/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 3, '2996'),
('BGT01', 'Brau- und Getränketechnologe/-login EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '12193'),
('BUH01', 'Buchhändler/in EFZ', 'Verkauf/Einkauf', 'EFZ', NULL, '{}', 3, '3048'),
('BUM01', 'Büchsenmacher/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3657'),
('BUT01', 'Bühnentänzer/in EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 3, '7669'),
('CLK01', 'Carrosserielackierer/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 3, '3027'),
('CRR01', 'Carrosseriereparateur/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 3, '11552'),
('CSP01', 'Carrosseriespengler/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '2916'),
('CPT01', 'Chemie- und Pharmatechnologe/-login EFZ', 'Chemie/Physik', 'EFZ', NULL, '{}', 3, '3750'),
('COI01', 'Coiffeur/-euse EFZ', 'Schönheit/Sport', 'EFZ', NULL, '{}', 3, '3037'),
('DCD01', 'Dachdecker/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '9947'),
('DAS01', 'Dentalassistent/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 3, '3092'),
('71300', 'Detailhandelsfachmann/-frau EFZ', 'Verkauf/Einkauf', 'EFZ', 'Detailhandelsfachleute beraten Kunden, bewirtschaften Waren und gestalten Verkaufsflächen.', '{"realistic": 0.3, "investigative": 0.2, "artistic": 0.3, "social": 0.7, "enterprising": 0.7, "conventional": 0.4}', 3, '5130'),
('DRO01', 'Drogist/in EFZ', 'Verkauf/Einkauf', 'EFZ', NULL, '{}', 4, '3059'),
('DRA01', 'Druckausrüster/in EFZ', 'Druck', 'EFZ', NULL, '{}', 3, '11606'),
('EDF01', 'Edelsteinfasser/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11574'),
('46500', 'Elektroinstallateur/in EFZ', 'Elektrotechnik', 'EFZ', 'Elektroinstallateur/innen planen und installieren elektrische Anlagen in Gebäuden.', '{"realistic": 0.9, "investigative": 0.4, "artistic": 0.1, "social": 0.3, "enterprising": 0.3, "conventional": 0.4}', 4, '3062'),
('ELK01', 'Elektroniker/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 4, '4039'),
('ELP01', 'Elektroplaner/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 4, '3063'),
('ENT01', 'Entwässerungstechnologe/-login EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '8336'),
('EDB01', 'Entwickler/in digitales Business EFZ', 'Wirtschaft/Verwaltung', 'EFZ', NULL, '{}', 3, '11873'),
('FAP01', 'Fachmann/-frau Apotheke EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 3, '3747'),
('FBT01', 'Fachmann/-frau Bahntransport EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '11986'),
('94300', 'Fachmann/-frau Betreuung EFZ', 'Bildung/Soziales', 'EFZ', 'FaBe betreuen Kinder, Jugendliche, Menschen mit Beeinträchtigung oder betagte Menschen.', '{"realistic": 0.3, "investigative": 0.2, "artistic": 0.3, "social": 0.9, "enterprising": 0.2, "conventional": 0.3}', 3, '6196'),
('FBU01', 'Fachmann/-frau Betriebsunterhalt EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '3047'),
('FBG01', 'Fachmann/-frau Bewegungs- und Gesundheitsförderung EFZ', 'Schönheit/Sport', 'EFZ', NULL, '{}', 3, '8100'),
('86914', 'Fachmann/-frau Gesundheit EFZ', 'Gesundheit', 'EFZ', 'FaGe pflegen und betreuen Patientinnen und Patienten in Spitälern, Heimen oder der Spitex.', '{"realistic": 0.4, "investigative": 0.3, "artistic": 0.1, "social": 0.9, "enterprising": 0.2, "conventional": 0.4}', 3, '3270'),
('FHH01', 'Fachmann/-frau Hotellerie-Hauswirtschaft EFZ', 'Gastgewerbe', 'EFZ', NULL, '{}', 3, '5609'),
('FID01', 'Fachmann/-frau Information und Dokumentation EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 3, '2917'),
('FKD01', 'Fachmann/-frau Kundendialog EFZ', 'Wirtschaft/Verwaltung', 'EFZ', NULL, '{}', 3, '7944'),
('FLT01', 'Fachmann/-frau Leder und Textil EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 4, '8054'),
('FOV01', 'Fachmann/-frau öffentlicher Verkehr EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '8506'),
('FRT01', 'Fachmann/-frau Reinigungstechnik EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2997'),
('FSS01', 'Fachmann/-frau Sonnenschutz und Storentechnik EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '9950'),
('FTP01', 'Fachmann/-frau Textilpflege EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '3212'),
('FRM01', 'Fahrradmechaniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '8108'),
('FSL01', 'Fahrzeugschlosser/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '2948'),
('FSB01', 'Fassadenbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '9948'),
('FWO01', 'Feinwerkoptiker/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3620'),
('FLF01', 'Fleischfachmann/-frau EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '3625'),
('FLO01', 'Florist/in EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '3753'),
('FMB01', 'Formenbauer/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3632'),
('FSW01', 'Forstwart/in EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '3758'),
('FOT01', 'Fotograf/in EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 4, '3084'),
('FMF01', 'Fotomedienfachmann/-frau EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 4, '5605'),
('17000', 'Gärtner/in EFZ', 'Natur', 'EFZ', 'Gärtner/innen pflegen Pflanzen, gestalten Gärten und Grünanlagen.', '{"realistic": 0.9, "investigative": 0.3, "artistic": 0.5, "social": 0.2, "enterprising": 0.2, "conventional": 0.2}', 3, '2946'),
('GBI01', 'Gebäudeinformatiker/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '4061'),
('GTH01', 'Gebäudetechnikplaner/in Heizung EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '2985'),
('GTL01', 'Gebäudetechnikplaner/in Lüftung EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '7813'),
('GTS01', 'Gebäudetechnikplaner/in Sanitär EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '7814'),
('GGB01', 'Geigenbauer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '4047'),
('GMG01', 'Gemüsegärtner/in EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '2979'),
('GEO01', 'Geomatiker/in EFZ', 'Planung/Konstruktion', 'EFZ', NULL, '{}', 4, '3654'),
('GRB01', 'Gerüstbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '9949'),
('GWT01', 'Gestalter/in Werbetechnik EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '3854'),
('GWG01', 'Gewebegestalter/in EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '3938'),
('GTB01', 'Gipser/in-Trockenbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2930'),
('GLA01', 'Glaser/in EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 4, '3117'),
('GLM01', 'Glasmaler/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '4045'),
('GLB01', 'Gleisbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '3017'),
('GOS01', 'Goldschmied/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '7766'),
('64700', 'Grafiker/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', 'Grafiker/innen gestalten visuelle Kommunikationsmittel wie Plakate, Logos und Websites.', '{"realistic": 0.2, "investigative": 0.3, "artistic": 0.9, "social": 0.3, "enterprising": 0.3, "conventional": 0.3}', 4, '3763'),
('GRV01', 'Graveur/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '3112'),
('GDB01', 'Grundbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2894'),
('GSF01', 'Gussformer/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 3, '3021'),
('GST01', 'Gusstechnologe/-login EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3019'),
('HZI01', 'Heizungsinstallateur/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2983'),
('HBH01', 'Holzbildhauer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '3087'),
('HHW01', 'Holzhandwerker/in EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 3, '7697'),
('HIF01', 'Holzindustriefachmann/-frau EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 3, '3166'),
('HSA01', 'Hörsystemakustiker/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 3, '9841'),
('HKF01', 'Hotel-Kommunikationsfachmann/-frau EFZ', 'Gastgewerbe', 'EFZ', NULL, '{}', 3, '10353'),
('HFS01', 'Hufschmied/in EFZ', 'Natur', 'EFZ', NULL, '{}', 4, '4017'),
('88900', 'ICT-Fachmann/-frau EFZ', 'Informatik', 'EFZ', 'ICT-Fachleute installieren, konfigurieren und warten Informatikmittel.', '{"realistic": 0.6, "investigative": 0.6, "artistic": 0.1, "social": 0.3, "enterprising": 0.2, "conventional": 0.5}', 3, '10631'),
('IUB01', 'Industrie- und Unterlagsbodenbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2895'),
('IKR01', 'Industriekeramiker/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 3, '2908'),
('ILK01', 'Industrielackierer/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 3, '3695'),
('IPO01', 'Industriepolsterer/-polsterin EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '3155'),
('88611', 'Informatiker/in EFZ', 'Informatik', 'EFZ', 'Informatikerinnen und Informatiker EFZ bieten Lösungen für Informations- und Kommunikationstechnologien an.', '{"realistic": 0.3, "investigative": 0.9, "artistic": 0.4, "social": 0.2, "enterprising": 0.3, "conventional": 0.5}', 4, '7671'),
('64800', 'Interactive Media Designer EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', 'Interactive Media Designer gestalten digitale Medienprodukte und Benutzeroberflächen.', '{"realistic": 0.2, "investigative": 0.5, "artistic": 0.9, "social": 0.3, "enterprising": 0.3, "conventional": 0.3}', 4, '3917'),
('ISP01', 'Isolierspengler/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '2915'),
('KSM01', 'Kältesystem-Monteur/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '2984'),
('KSP01', 'Kältesystem-Planer/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '7812'),
('KMF01', 'Kaminfeger/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2990'),
('KBS01', 'Kapitän/in der Binnenschifffahrt EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '11817'),
('68500', 'Kaufmann/-frau EFZ', 'Wirtschaft/Verwaltung', 'EFZ', 'Kaufleute arbeiten in verschiedenen Branchen und erledigen administrative und organisatorische Aufgaben.', '{"realistic": 0.2, "investigative": 0.3, "artistic": 0.1, "social": 0.4, "enterprising": 0.5, "conventional": 0.8}', 3, '3104'),
('KER01', 'Keramiker/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '4026'),
('KLB01', 'Klavierbauer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11226'),
('79000', 'Koch/Köchin EFZ', 'Gastgewerbe', 'EFZ', 'Köche/Köchinnen bereiten Speisen zu, planen Menüs und bewirtschaften die Küche.', '{"realistic": 0.7, "investigative": 0.2, "artistic": 0.6, "social": 0.4, "enterprising": 0.3, "conventional": 0.3}', 3, '2992'),
('KON01', 'Konstrukteur/in EFZ', 'Planung/Konstruktion', 'EFZ', NULL, '{}', 4, '3699'),
('KFW01', 'Korb- und Flechtwerkgestalter/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 3, '4051'),
('KOS01', 'Kosmetiker/in EFZ', 'Schönheit/Sport', 'EFZ', NULL, '{}', 3, '3026'),
('KUF01', 'Küfer/in EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 4, '3141'),
('KST01', 'Kunststofftechnologe/-login EFZ', 'Chemie/Physik', 'EFZ', NULL, '{}', 4, '3015'),
('LAB01', 'Laborant/in EFZ', 'Chemie/Physik', 'EFZ', NULL, '{}', 3, '7354'),
('LMM01', 'Landmaschinenmechaniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '3138'),
('15000', 'Landwirt/in EFZ', 'Natur', 'EFZ', 'Landwirt/innen bewirtschaften einen Bauernhof und produzieren Nahrungsmittel.', '{"realistic": 0.9, "investigative": 0.3, "artistic": 0.1, "social": 0.2, "enterprising": 0.5, "conventional": 0.3}', 3, '3878'),
('LMT01', 'Lebensmitteltechnologe/-login EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '3696'),
('95600', 'Logistiker/in EFZ', 'Verkehr/Logistik', 'EFZ', 'Logistiker/innen nehmen Güter an, kontrollieren, lagern und verteilen sie.', '{"realistic": 0.7, "investigative": 0.2, "artistic": 0.1, "social": 0.3, "enterprising": 0.3, "conventional": 0.7}', 3, '3804'),
('LAB02', 'Lüftungsanlagenbauer/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2918'),
('MAL01', 'Maler/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2988'),
('88613', 'Mediamatiker/in EFZ', 'Informatik', 'EFZ', 'Mediamatiker/innen gestalten Medieninhalte, pflegen Webseiten und erstellen Marketingmaterial.', '{"realistic": 0.2, "investigative": 0.5, "artistic": 0.8, "social": 0.4, "enterprising": 0.5, "conventional": 0.3}', 4, '4034'),
('MDT01', 'Medientechnologe/-login EFZ', 'Druck', 'EFZ', NULL, '{}', 4, '10767'),
('86930', 'Medizinische/r Praxisassistent/in EFZ', 'Gesundheit', 'EFZ', 'MPA arbeiten in Arztpraxen und erledigen medizinische und administrative Aufgaben.', '{"realistic": 0.3, "investigative": 0.4, "artistic": 0.1, "social": 0.8, "enterprising": 0.3, "conventional": 0.6}', 3, '2899'),
('MPT01', 'Medizinproduktetechnologe/-login EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 3, '10361'),
('MSM01', 'Messerschmied/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '2959'),
('MBR01', 'Metallbauer/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '2966'),
('MBK01', 'Metallbaukonstrukteur/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3702'),
('MKM01', 'Mikromechaniker/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '2904'),
('MKZ01', 'Mikrozeichner/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3142'),
('MLT01', 'Milchtechnologe/-login EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '3813'),
('MEL01', 'Montage-Elektriker/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 3, '3145'),
('MGM01', 'Motorgerätemechaniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '3146'),
('MRM01', 'Motorradmechaniker/in EFZ', 'Fahrzeuge', 'EFZ', NULL, '{}', 4, '3147'),
('MUL01', 'Müller/in EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '3689'),
('MME01', 'Multimediaelektroniker/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 4, '4057'),
('NAF01', 'Nautische/r Fachmann/-frau EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '3783'),
('NEL01', 'Netzelektriker/in EFZ', 'Elektrotechnik', 'EFZ', NULL, '{}', 4, '3745'),
('OBB01', 'Oberflächenbeschichter/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 3, '3694'),
('OVU01', 'Oberflächenveredler/in Uhren und Schmuck EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3217'),
('OBF01', 'Obstfachmann/-frau EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '3184'),
('OFB01', 'Ofenbauer/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2909'),
('ORG01', 'Orgelbauer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11089'),
('OSM01', 'Orthopädieschuhmacher/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 4, '3174'),
('ORT01', 'Orthopädist/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 4, '3914'),
('PAP01', 'Papiertechnologe/-login EFZ', 'Druck', 'EFZ', NULL, '{}', 3, '3002'),
('PFF01', 'Pferdefachmann/-frau EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '7477'),
('PFL01', 'Pflästerer/Pflästerin EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2893'),
('PHY01', 'Physiklaborant/in EFZ', 'Chemie/Physik', 'EFZ', NULL, '{}', 4, '3153'),
('PLT01', 'Plattenleger/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2929'),
('POD01', 'Podologe/-login EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 3, '3829'),
('PD301', 'Polydesigner/in 3D EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '4030'),
('PGR01', 'Polygraf/in EFZ', 'Druck', 'EFZ', NULL, '{}', 4, '3156'),
('45700', 'Polymechaniker/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', 'Polymechaniker/innen fertigen Werkstücke, bauen Maschinen zusammen und führen Messungen durch.', '{"realistic": 0.9, "investigative": 0.6, "artistic": 0.1, "social": 0.2, "enterprising": 0.2, "conventional": 0.5}', 4, '3656'),
('45800', 'Produktionsmechaniker/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', 'Produktionsmechaniker/innen fertigen Einzelteile und bearbeiten verschiedene Werkstoffe.', '{"realistic": 0.9, "investigative": 0.4, "artistic": 0.1, "social": 0.2, "enterprising": 0.1, "conventional": 0.5}', 4, '3741'),
('QMT01', 'Qualitätsfachmann/-frau in Mikrotechnik EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '11282'),
('RAU01', 'Raumausstatter/in EFZ', 'Holz/Innenausbau', 'EFZ', NULL, '{}', 4, '2926'),
('RCY01', 'Recyclist/in EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '3336'),
('79100', 'Restaurantfachmann/-frau EFZ', 'Gastgewerbe', 'EFZ', 'Restaurantfachleute bedienen Gäste, beraten bei der Menüwahl und organisieren den Service.', '{"realistic": 0.3, "investigative": 0.1, "artistic": 0.2, "social": 0.8, "enterprising": 0.6, "conventional": 0.3}', 3, '5604'),
('SNI01', 'Sanitärinstallateur/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '2914'),
('51700', 'Schreiner/in EFZ', 'Holz/Innenausbau', 'EFZ', 'Schreiner/innen stellen Möbel, Türen, Fenster und Innenausbauten aus Holz her.', '{"realistic": 0.9, "investigative": 0.3, "artistic": 0.6, "social": 0.2, "enterprising": 0.2, "conventional": 0.3}', 4, '2925'),
('SHM01', 'Schuhmacher/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 3, '3909'),
('SBM01', 'Seilbahn-Mechatroniker/in EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 4, '6694'),
('SLS01', 'Silberschmied/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11572'),
('SOI01', 'Solarinstallateur/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 3, '11929'),
('SPG01', 'Spengler/in EFZ', 'Gebäudetechnik', 'EFZ', NULL, '{}', 4, '2911'),
('STM01', 'Steinmetz/in EFZ', 'Bau', 'EFZ', NULL, '{}', 4, '3789'),
('STB01', 'Strassenbauer/in EFZ', 'Bau', 'EFZ', NULL, '{}', 3, '2892'),
('STF01', 'Strassentransportfachmann/-frau EFZ', 'Verkehr/Logistik', 'EFZ', NULL, '{}', 3, '3881'),
('SGF01', 'Systemgastronomiefachmann/-frau EFZ', 'Gastgewerbe', 'EFZ', NULL, '{}', 3, '8237'),
('TXT01', 'Textiltechnologe/-login EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '7053'),
('THM01', 'Theatermaler/in EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 4, '3855'),
('TMP01', 'Tiermedizinische/r Praxisassistent/in EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '3873'),
('TPF01', 'Tierpfleger/in EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '3975'),
('UHR01', 'Uhrmacher/in EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 4, '3218'),
('UHP01', 'Uhrmacher/in Produktion EFZ', 'Metall/Maschinen/Uhren', 'EFZ', NULL, '{}', 3, '3089'),
('VFF01', 'Veranstaltungsfachmann/-frau EFZ', 'Kultur/Medien', 'EFZ', NULL, '{}', 3, '7986'),
('VGE01', 'Vergolder/in-Einrahmer/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '4043'),
('VPD01', 'Verpackungsdrucker/in EFZ', 'Druck', 'EFZ', NULL, '{}', 3, '2955'),
('VPT01', 'Verpackungstechnologe/-login EFZ', 'Nahrung', 'EFZ', NULL, '{}', 3, '2999'),
('WFF01', 'Weinfachmann/-frau EFZ', 'Natur', 'EFZ', NULL, '{}', 3, '2974'),
('WTG01', 'Wohntextilgestalter/in EFZ', 'Textilien/Mode', 'EFZ', NULL, '{}', 3, '3129'),
('ZHT01', 'Zahntechniker/in EFZ', 'Gesundheit', 'EFZ', NULL, '{}', 4, '2900'),
('51200', 'Zimmermann/Zimmerin EFZ', 'Holz/Innenausbau', 'EFZ', 'Zimmerleute bauen Holzkonstruktionen für Gebäude, Brücken und Dachstühle.', '{"realistic": 0.9, "investigative": 0.3, "artistic": 0.3, "social": 0.3, "enterprising": 0.3, "conventional": 0.2}', 4, '3018'),
('ZPM01', 'Zinnpfeifenmacher/in EFZ', 'Gestaltung/Kunsthandwerk', 'EFZ', NULL, '{}', 4, '11090'),

-- ═══════════════════════════════════════════════════════════════
-- EBA PROFESSIONS (61)
-- ═══════════════════════════════════════════════════════════════

('ABDE1', 'Abdichtungspraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '9951'),
('AGRE1', 'Agrarpraktiker/in EBA', 'Natur', 'EBA', NULL, '{}', 2, '7640'),
('86916', 'Assistent/in Gesundheit und Soziales EBA', 'Gesundheit', 'EBA', 'AGS unterstützen Fachpersonen bei der Betreuung und Pflege von Menschen.', '{"realistic": 0.4, "investigative": 0.2, "artistic": 0.1, "social": 0.9, "enterprising": 0.1, "conventional": 0.3}', 2, '8506'),
('AUTE1', 'Automobil-Assistent/in EBA', 'Fahrzeuge', 'EBA', NULL, '{}', 2, '3038'),
('BKCE', 'Bäcker/in-Konditor/in-Confiseur/in EBA', 'Nahrung', 'EBA', NULL, '{}', 2, '7818'),
('BKNE1', 'Bekleidungsnäher/in EBA', 'Textilien/Mode', 'EBA', NULL, '{}', 2, '3834'),
('CHPE1', 'Chemie- und Pharmapraktiker/in EBA', 'Chemie/Physik', 'EBA', NULL, '{}', 2, '3759'),
('COIE1', 'Coiffeur/-euse EBA', 'Schönheit/Sport', 'EBA', NULL, '{}', 2, '7691'),
('DCPE1', 'Dachdeckerpraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '9951'),
('DKNE1', 'Dekorationsnäher/in EBA', 'Textilien/Mode', 'EBA', NULL, '{}', 2, '3130'),
('71400', 'Detailhandelsassistent/in EBA', 'Verkauf/Einkauf', 'EBA', 'Detailhandelsassistent/innen verkaufen Waren und kümmern sich um die Warenpräsentation.', '{"realistic": 0.3, "investigative": 0.1, "artistic": 0.2, "social": 0.7, "enterprising": 0.6, "conventional": 0.3}', 2, '7697'),
('ENTE1', 'Entwässerungspraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '8337'),
('FSBE1', 'Fassadenbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '9952'),
('FLAE1', 'Fleischfachassistent/in EBA', 'Nahrung', 'EBA', NULL, '{}', 2, '3626'),
('FLOE1', 'Florist/in EBA', 'Natur', 'EBA', NULL, '{}', 2, '7700'),
('FMPE1', 'Formenpraktiker/in EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '3633'),
('FSPE1', 'Forstpraktiker/in EBA', 'Natur', 'EBA', NULL, '{}', 2, '7696'),
('GTRE1', 'Gärtner/in EBA', 'Natur', 'EBA', NULL, '{}', 2, '7695'),
('GRBE1', 'Gerüstbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '9953'),
('GIPE1', 'Gipserpraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7693'),
('GLBE1', 'Gleisbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7694'),
('GDBE1', 'Grundbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7692'),
('HZPE1', 'Heizungspraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7701'),
('HLBE1', 'Holzbearbeiter/in EBA', 'Holz/Innenausbau', 'EBA', NULL, '{}', 2, '7698'),
('IUBE1', 'Industrie- und Unterlagsbodenbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7699'),
('KMPE1', 'Kältemontage-Praktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7702'),
('68600', 'Kaufmann/-frau EBA', 'Wirtschaft/Verwaltung', 'EBA', 'Kaufleute EBA unterstützen bei administrativen und organisatorischen Aufgaben in verschiedenen Branchen.', '{"realistic": 0.2, "investigative": 0.2, "artistic": 0.1, "social": 0.4, "enterprising": 0.4, "conventional": 0.8}', 2, '7703'),
('KUAE1', 'Küchenangestellte/r EBA', 'Gastgewerbe', 'EBA', NULL, '{}', 2, '5610'),
('KSPE1', 'Kunststoffpraktiker/in EBA', 'Chemie/Physik', 'EBA', NULL, '{}', 2, '7704'),
('LAKE1', 'Lackierassistent/in EBA', 'Fahrzeuge', 'EBA', NULL, '{}', 2, '7819'),
('LMPE1', 'Lebensmittelpraktiker/in EBA', 'Nahrung', 'EBA', NULL, '{}', 2, '7705'),
('95700', 'Logistiker/in EBA', 'Verkehr/Logistik', 'EBA', 'Logistiker/innen EBA arbeiten in Lagern und transportieren Güter.', '{"realistic": 0.8, "investigative": 0.1, "artistic": 0.1, "social": 0.2, "enterprising": 0.2, "conventional": 0.6}', 2, '7706'),
('LAPE1', 'Lüftungsanlagenpraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7707'),
('MLPE1', 'Malerpraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7708'),
('MARE1', 'Maurer/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7709'),
('MCPE1', 'Mechanikpraktiker/in EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '7710'),
('MBPE1', 'Metallbaupraktiker/in EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '7711'),
('MLPE2', 'Milchpraktiker/in EBA', 'Nahrung', 'EBA', NULL, '{}', 2, '7712'),
('MSSE1', 'Montagepraktiker/in Sonnenschutz und Storentechnik EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '9954'),
('OFPE1', 'Oberflächenpraktiker/in EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '7713'),
('PFWE1', 'Pferdewart/in EBA', 'Natur', 'EBA', NULL, '{}', 2, '7714'),
('PLPE1', 'Plattenlegerpraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7715'),
('POLE1', 'Polisseur/-euse EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '7716'),
('PHHE1', 'Praktiker/in Hotellerie-Hauswirtschaft EBA', 'Gastgewerbe', 'EBA', NULL, '{}', 2, '5611'),
('PRTE1', 'Praktiker/in Reinigungstechnik EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7717'),
('PMPE1', 'Printmedienpraktiker/in EBA', 'Druck', 'EBA', NULL, '{}', 2, '7718'),
('RFPE1', 'Reifenpraktiker/in EBA', 'Fahrzeuge', 'EBA', NULL, '{}', 2, '7719'),
('RANE1', 'Restaurantangestellte/r EBA', 'Gastgewerbe', 'EBA', NULL, '{}', 2, '5612'),
('SNPE1', 'Sanitärpraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7720'),
('SCPE1', 'Schreinerpraktiker/in EBA', 'Holz/Innenausbau', 'EBA', NULL, '{}', 2, '7721'),
('SBLE1', 'Seilbahner/in EBA', 'Verkehr/Logistik', 'EBA', NULL, '{}', 2, '7722'),
('SLME1', 'Solarmonteur/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '11930'),
('SPPE1', 'Spenglerpraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7723'),
('STSE1', 'Steinsetzer/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7724'),
('SBPE1', 'Strassenbaupraktiker/in EBA', 'Bau', 'EBA', NULL, '{}', 2, '7725'),
('STPE1', 'Strassentransportpraktiker/in EBA', 'Verkehr/Logistik', 'EBA', NULL, '{}', 2, '7726'),
('SGPE1', 'Systemgastronomiepraktiker/in EBA', 'Gastgewerbe', 'EBA', NULL, '{}', 2, '8238'),
('TXPE1', 'Textilpraktiker/in EBA', 'Textilien/Mode', 'EBA', NULL, '{}', 2, '7727'),
('UHAE1', 'Uhrenarbeiter/in EBA', 'Metall/Maschinen/Uhren', 'EBA', NULL, '{}', 2, '7728'),
('UHPE1', 'Unterhaltspraktiker/in EBA', 'Gebäudetechnik', 'EBA', NULL, '{}', 2, '7729'),
('ZRAE1', 'Zweirad-Assistent/in EBA', 'Fahrzeuge', 'EBA', NULL, '{}', 2, '7730')

ON CONFLICT (code) DO UPDATE SET
  name_de = EXCLUDED.name_de,
  field = EXCLUDED.field,
  education_type = EXCLUDED.education_type,
  description_de = COALESCE(EXCLUDED.description_de, berufe.description_de),
  personality_fit = CASE WHEN EXCLUDED.personality_fit::text = '{}' THEN berufe.personality_fit ELSE EXCLUDED.personality_fit END,
  duration_years = EXCLUDED.duration_years,
  bb_id = EXCLUDED.bb_id;
