import Foundation

struct LehrstelleCard: Identifiable, Codable, Hashable {
    let id: UUID
    let companyId: UUID
    let companyName: String
    let companyLogoUrl: String?
    let berufCode: String
    let berufTitle: String
    let title: String
    let description: String
    let canton: String
    let city: String
    let educationType: EducationType
    let startDate: Date?
    let durationYears: Int
    let videoUrl: String?
    let photoUrls: [String]
    let cultureDescription: String?
    let cultureTags: [String]
    let requirements: [String]
    let compatibilityScore: Double
    let berufsschuleCanton: String?
    let companySize: CompanySize?
    let isVerified: Bool
    let isPremium: Bool

    // Map / geo fields (optional — older API responses still decode)
    var workplaceAddress: String?
    var lat: Double?
    var lng: Double?
    var berufsschuleId: UUID?
    var berufsschuleDays: String?
    var berufCategory: String?

    var compatibilityPercentage: Int {
        Int(compatibilityScore * 100)
    }

    var locationDisplay: String {
        "\(city), \(canton)"
    }

    var primaryPhotoUrl: URL? {
        guard let first = photoUrls.first else { return nil }
        return URL(string: first)
    }

    var companyLogoURL: URL? {
        guard let logo = companyLogoUrl else { return nil }
        return URL(string: logo)
    }

    var hasCoordinates: Bool {
        lat != nil && lng != nil
    }
}

enum EducationType: String, Codable {
    case efz = "EFZ"
    case eba = "EBA"

    var displayName: String {
        switch self {
        case .efz: "EFZ (3-4 Jahre)"
        case .eba: "EBA (2 Jahre)"
        }
    }
}

enum CompanySize: String, Codable {
    case small = "small"       // 1-50
    case medium = "medium"     // 51-250
    case large = "large"       // 250+

    var displayName: String {
        switch self {
        case .small: "Kleinunternehmen"
        case .medium: "Mittelgrosses Unternehmen"
        case .large: "Grossunternehmen"
        }
    }
}

// MARK: - Sample Data

extension LehrstelleCard {
    static let samples: [LehrstelleCard] = [

        // MARK: – Informatik (4 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Swisscom AG",
            companyLogoUrl: nil,
            berufCode: "88611",
            berufTitle: "Informatiker/in EFZ",
            title: "Informatiker/in EFZ Applikationsentwicklung",
            description: "Entwickle moderne Apps und Webservices in einem agilen Team. Du arbeitest an echten Kundenprojekten und lernst die neusten Technologien kennen.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Innovation, Teamwork und Nachhaltigkeit sind unsere Werte.",
            cultureTags: ["Innovation", "Teamwork", "Flexibel"],
            requirements: ["Sek A / Niveau E", "Gute Noten in Mathe", "Interesse an Technologie"],
            compatibilityScore: 0.91,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Hardturmstrasse 3, 8005 Zürich",
            lat: 47.3769,
            lng: 8.5417,
            berufCategory: "informatik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Google Zürich",
            companyLogoUrl: nil,
            berufCode: "88612",
            berufTitle: "Informatiker/in EFZ",
            title: "Informatiker/in EFZ Plattformentwicklung",
            description: "Arbeite bei einem der innovativsten Technologieunternehmen der Welt. Du lernst Cloud-Infrastruktur, Netzwerke und Systemadministration.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Offene Kultur, flache Hierarchien und viel Raum für Kreativität.",
            cultureTags: ["Innovation", "International", "Kreativ"],
            requirements: ["Sek A", "Sehr gute Englischkenntnisse", "Logisches Denken"],
            compatibilityScore: 0.95,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Brandschenkestrasse 110, 8002 Zürich",
            lat: 47.3654,
            lng: 8.5247,
            berufCategory: "informatik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "IT-Solutions Zug AG",
            companyLogoUrl: nil,
            berufCode: "88900",
            berufTitle: "ICT-Fachfrau/-mann EFZ",
            title: "ICT-Fachfrau/-mann EFZ",
            description: "Unterstütze unsere Kunden bei IT-Problemen und lerne, wie man Netzwerke aufbaut und betreut. Abwechslungsreicher Alltag garantiert.",
            canton: "LU",
            city: "Luzern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Junges Team, lockere Atmosphäre und spannende Kundenprojekte.",
            cultureTags: ["Kundenkontakt", "Abwechslung", "Teamwork"],
            requirements: ["Sek A oder B", "Technisches Verständnis", "Kommunikationsfähigkeit"],
            compatibilityScore: 0.78,
            berufsschuleCanton: "LU",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Industriestrasse 21, 6005 Luzern",
            lat: 47.0502,
            lng: 8.3093,
            berufCategory: "informatik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "SBB",
            companyLogoUrl: nil,
            berufCode: "88613",
            berufTitle: "Mediamatiker/in EFZ",
            title: "Mediamatiker/in EFZ",
            description: "Gestalte Inhalte für Web, Social Media und interne Kommunikation. Du kombinierst Kreativität mit Technik bei der grössten Arbeitgeberin der Schweiz.",
            canton: "BE",
            city: "Bern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Vielfalt, Verlässlichkeit und Zukunftsorientierung.",
            cultureTags: ["Kreativ", "Vielfältig", "Zukunftsorientiert"],
            requirements: ["Sek A", "Kreativität", "Gute Deutschkenntnisse"],
            compatibilityScore: 0.82,
            berufsschuleCanton: "BE",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Hilfikerstrasse 1, 3000 Bern",
            lat: 46.9480,
            lng: 7.4474,
            berufCategory: "informatik"
        ),

        // MARK: – Gesundheit (3 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Universitätsspital Zürich",
            companyLogoUrl: nil,
            berufCode: "86914",
            berufTitle: "Fachfrau/-mann Gesundheit EFZ",
            title: "FaGe – Fachfrau/-mann Gesundheit EFZ",
            description: "Pflege Menschen und mache einen Unterschied. Am USZ erwartet dich ein vielseitiger Ausbildungsplatz mit modernster Infrastruktur.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Menschlichkeit, Professionalität, Innovation in der Medizin.",
            cultureTags: ["Gesundheit", "Menschen helfen", "Vielseitig"],
            requirements: ["Sek A oder B", "Empathie", "Teamfähigkeit", "Belastbarkeit"],
            compatibilityScore: 0.74,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Rämistrasse 100, 8091 Zürich",
            lat: 47.3764,
            lng: 8.5489,
            berufCategory: "gesundheit"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Inselspital Bern",
            companyLogoUrl: nil,
            berufCode: "86914",
            berufTitle: "Fachfrau/-mann Gesundheit EFZ",
            title: "FaGe – Fachfrau/-mann Gesundheit EFZ",
            description: "Das Inselspital bietet dir eine erstklassige Ausbildung im Gesundheitswesen. Du durchläufst verschiedene Abteilungen und lernst den Spitalalltag kennen.",
            canton: "BE",
            city: "Bern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Engagement für Patienten, interdisziplinäre Zusammenarbeit.",
            cultureTags: ["Teamwork", "Verantwortung", "Abwechslung"],
            requirements: ["Sek B oder höher", "Einfühlungsvermögen", "Zuverlässigkeit"],
            compatibilityScore: 0.71,
            berufsschuleCanton: "BE",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Freiburgstrasse 18, 3010 Bern",
            lat: 46.9472,
            lng: 7.4256,
            berufCategory: "gesundheit"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Kantonsspital Winterthur",
            companyLogoUrl: nil,
            berufCode: "86930",
            berufTitle: "Assistent/in Gesundheit und Soziales EBA",
            title: "AGS – Assistent/in Gesundheit und Soziales EBA",
            description: "Steige mit einer zweijährigen Grundbildung ins Gesundheitswesen ein. Du unterstützt das Pflegeteam und sammelst wertvolle Praxiserfahrung.",
            canton: "ZH",
            city: "Winterthur",
            educationType: .eba,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 2,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Wertschätzung, Förderung und ein guter Einstieg in die Pflege.",
            cultureTags: ["Einstieg", "Praxisnah", "Unterstützend"],
            requirements: ["Abgeschlossene Volksschule", "Freude am Umgang mit Menschen", "Teamfähigkeit"],
            compatibilityScore: 0.63,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Brauerstrasse 15, 8401 Winterthur",
            lat: 47.4984,
            lng: 8.7238,
            berufCategory: "gesundheit"
        ),

        // MARK: – Kaufmännisch (3 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "UBS",
            companyLogoUrl: nil,
            berufCode: "68500",
            berufTitle: "Kauffrau/-mann EFZ",
            title: "Kauffrau/-mann EFZ Dienstleistung und Administration",
            description: "Erhalte eine vielseitige kaufmännische Ausbildung bei einer der grössten Banken der Welt. Du durchläufst verschiedene Abteilungen und lernst die Finanzwelt kennen.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Professionalität, Weiterentwicklung und globale Perspektiven.",
            cultureTags: ["Karrierechancen", "International", "Professionell"],
            requirements: ["Sek A", "Gute Fremdsprachenkenntnisse", "Zuverlässigkeit"],
            compatibilityScore: 0.84,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Bahnhofstrasse 45, 8001 Zürich",
            lat: 47.3713,
            lng: 8.5392,
            berufCategory: "kaufmännisch"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Post CH AG",
            companyLogoUrl: nil,
            berufCode: "68500",
            berufTitle: "Kauffrau/-mann EFZ",
            title: "Kauffrau/-mann EFZ",
            description: "Bei der Post erwartet dich eine abwechslungsreiche Ausbildung mit Einblicken in Logistik, Kundenservice und Verwaltung.",
            canton: "BE",
            city: "Bern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Vielfalt, Nachhaltigkeit und Kundennähe.",
            cultureTags: ["Vielfältig", "Nachhaltig", "Kundennah"],
            requirements: ["Sek A oder B", "Organisationsfähigkeit", "Gute Deutschkenntnisse"],
            compatibilityScore: 0.77,
            berufsschuleCanton: "BE",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Wankdorfallee 4, 3030 Bern",
            lat: 46.9633,
            lng: 7.4688,
            berufCategory: "kaufmännisch"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Migros",
            companyLogoUrl: nil,
            berufCode: "68500",
            berufTitle: "Kauffrau/-mann EFZ",
            title: "Kauffrau/-mann EFZ Branche Handel",
            description: "Lerne die vielfältige Welt des Detailhandels von der kaufmännischen Seite kennen. Du arbeitest in verschiedenen Bereichen wie Einkauf, Marketing und Personal.",
            canton: "AG",
            city: "Aarau",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Nachhaltigkeit, Respekt und Förderung junger Talente.",
            cultureTags: ["Nachhaltig", "Fördernd", "Teamorientiert"],
            requirements: ["Sek A oder B", "Freude am Organisieren", "Teamfähigkeit"],
            compatibilityScore: 0.73,
            berufsschuleCanton: "AG",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Industriestrasse 20, 5000 Aarau",
            lat: 47.3925,
            lng: 8.0444,
            berufCategory: "kaufmännisch"
        ),

        // MARK: – Technik (3 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "ABB Schweiz",
            companyLogoUrl: nil,
            berufCode: "45700",
            berufTitle: "Polymechaniker/in EFZ",
            title: "Polymechaniker/in EFZ",
            description: "Fertige Präzisionsteile und Baugruppen an modernen CNC-Maschinen. Du lernst den gesamten Produktionsprozess von der Zeichnung bis zum fertigen Werkstück.",
            canton: "AG",
            city: "Baden",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Technologieführer mit starkem Ausbildungsengagement.",
            cultureTags: ["Hightech", "Präzision", "Karrierechancen"],
            requirements: ["Sek A", "Gute Noten in Mathe und Physik", "Handwerkliches Geschick"],
            compatibilityScore: 0.86,
            berufsschuleCanton: "AG",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Brown Boveri Strasse 6, 5400 Baden",
            lat: 47.4734,
            lng: 8.3064,
            berufCategory: "technik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Elektro Meier GmbH",
            companyLogoUrl: nil,
            berufCode: "47600",
            berufTitle: "Elektroinstallateur/in EFZ",
            title: "Elektroinstallateur/in EFZ",
            description: "Installiere elektrische Anlagen in Neubauten und Renovationsprojekten. Du lernst alles von der Planung bis zur Inbetriebnahme.",
            canton: "SG",
            city: "St. Gallen",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Familienbetrieb mit viel Praxiserfahrung auf der Baustelle.",
            cultureTags: ["Praxisnah", "Familiär", "Abwechslung"],
            requirements: ["Sek A oder B", "Handwerkliches Geschick", "Schwindelfreiheit"],
            compatibilityScore: 0.69,
            berufsschuleCanton: "SG",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Rorschacher Strasse 150, 9006 St. Gallen",
            lat: 47.4245,
            lng: 9.3767,
            berufCategory: "technik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Siemens Schweiz",
            companyLogoUrl: nil,
            berufCode: "46500",
            berufTitle: "Automatiker/in EFZ",
            title: "Automatiker/in EFZ",
            description: "Entwickle und programmiere automatisierte Steuerungen für industrielle Anlagen. Du verbindest Elektrotechnik mit Software-Programmierung.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Zukunftstechnologie, globales Netzwerk und starke Ausbildung.",
            cultureTags: ["Hightech", "International", "Zukunftsorientiert"],
            requirements: ["Sek A", "Interesse an Technik und Programmierung", "Analytisches Denken"],
            compatibilityScore: 0.88,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Freilagerstrasse 40, 8047 Zürich",
            lat: 47.3830,
            lng: 8.4980,
            berufCategory: "technik"
        ),

        // MARK: – Design (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Designstudio Helvetia",
            companyLogoUrl: nil,
            berufCode: "64700",
            berufTitle: "Grafiker/in EFZ",
            title: "Grafiker/in EFZ",
            description: "Gestalte visuelle Kommunikation für namhafte Kunden. Du lernst Typografie, Layout und digitale Mediengestaltung in einem kreativen Umfeld.",
            canton: "BS",
            city: "Basel",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Kreatives Atelier mit inspirierender Atmosphäre.",
            cultureTags: ["Kreativ", "Inspirierend", "Gestalterisch"],
            requirements: ["Sek A", "Gestalterische Begabung", "Zeichnerische Fähigkeiten", "Portfolio"],
            compatibilityScore: 0.80,
            berufsschuleCanton: "BS",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Gerbergasse 30, 4001 Basel",
            lat: 47.5596,
            lng: 7.5886,
            berufCategory: "design"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Post CH AG",
            companyLogoUrl: nil,
            berufCode: "64800",
            berufTitle: "Interactive Media Designer EFZ",
            title: "Interactive Media Designer EFZ",
            description: "Gestalte digitale Erlebnisse und Benutzeroberflächen. Du arbeitest an Webseiten, Apps und interaktiven Medien für Millionen von Nutzern.",
            canton: "BE",
            city: "Bern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Digitale Transformation, kreative Freiräume und agile Teams.",
            cultureTags: ["Digital", "Kreativ", "Agil"],
            requirements: ["Sek A", "Gestalterisches Flair", "Interesse an digitalen Medien"],
            compatibilityScore: 0.85,
            berufsschuleCanton: "BE",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Wankdorfallee 4, 3030 Bern",
            lat: 46.9633,
            lng: 7.4688,
            berufCategory: "design"
        ),

        // MARK: – Gastronomie (3 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Bäckerei Müller",
            companyLogoUrl: nil,
            berufCode: "21104",
            berufTitle: "Bäcker/in-Konditor/in EFZ",
            title: "Bäcker/in-Konditor/in EFZ",
            description: "Werde Teil unserer Familientradition! Seit 1956 backen wir mit Leidenschaft. Lerne das Handwerk von Grund auf und kreiere eigene Rezepte.",
            canton: "BE",
            city: "Thun",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Familiäres Umfeld, Handwerkskunst und Tradition.",
            cultureTags: ["Familiär", "Handwerk", "Tradition"],
            requirements: ["Sek B", "Teamfähigkeit", "Frühaufsteher/in"],
            compatibilityScore: 0.62,
            berufsschuleCanton: "BE",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Bälliz 42, 3600 Thun",
            lat: 46.7580,
            lng: 7.6280,
            berufCategory: "gastronomie"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Restaurant Alpenhof",
            companyLogoUrl: nil,
            berufCode: "79000",
            berufTitle: "Koch/Köchin EFZ",
            title: "Koch/Köchin EFZ",
            description: "Koche mit regionalen und saisonalen Produkten in einem ausgezeichneten Restaurant. Du lernst klassische und moderne Kochtechniken.",
            canton: "GR",
            city: "Chur",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Leidenschaft fürs Kochen, Qualität und regionale Produkte.",
            cultureTags: ["Kulinarik", "Regional", "Leidenschaft"],
            requirements: ["Sek B", "Belastbarkeit", "Kreativität", "Teamfähigkeit"],
            compatibilityScore: 0.67,
            berufsschuleCanton: "GR",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Reichsgasse 11, 7000 Chur",
            lat: 46.8499,
            lng: 9.5329,
            berufCategory: "gastronomie"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Café Bernina",
            companyLogoUrl: nil,
            berufCode: "79000",
            berufTitle: "Koch/Köchin EFZ",
            title: "Koch/Köchin EFZ",
            description: "Bereite Gerichte für unser beliebtes Café-Restaurant zu. Kreativität und frische Zutaten stehen bei uns im Mittelpunkt.",
            canton: "SG",
            city: "St. Gallen",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Gemütliche Atmosphäre, kreatives Kochen und ein tolles Team.",
            cultureTags: ["Kreativ", "Gemütlich", "Teamwork"],
            requirements: ["Sek B", "Freude am Kochen", "Belastbarkeit"],
            compatibilityScore: 0.60,
            berufsschuleCanton: "SG",
            companySize: .small,
            isVerified: false,
            isPremium: false,
            workplaceAddress: "Marktgasse 22, 9000 St. Gallen",
            lat: 47.4237,
            lng: 9.3748,
            berufCategory: "gastronomie"
        ),

        // MARK: – Detailhandel (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Coop",
            companyLogoUrl: nil,
            berufCode: "71300",
            berufTitle: "Detailhandelsfachfrau/-mann EFZ",
            title: "Detailhandelsfachfrau/-mann EFZ",
            description: "Berate Kundinnen und Kunden, gestalte Verkaufsflächen und lerne alles über Warenwirtschaft. Eine abwechslungsreiche Ausbildung im Handel.",
            canton: "BS",
            city: "Basel",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Kundennähe, Nachhaltigkeit und Teamgeist.",
            cultureTags: ["Kundenkontakt", "Nachhaltig", "Teamgeist"],
            requirements: ["Sek B", "Freude am Kundenkontakt", "Zuverlässigkeit"],
            compatibilityScore: 0.66,
            berufsschuleCanton: "BS",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Pfeffingerstrasse 65, 4002 Basel",
            lat: 47.5476,
            lng: 7.5928,
            berufCategory: "detailhandel"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Migros",
            companyLogoUrl: nil,
            berufCode: "71300",
            berufTitle: "Detailhandelsassistent/in EBA",
            title: "Detailhandelsassistent/in EBA",
            description: "Starte deine Karriere im Detailhandel mit einer zweijährigen Grundbildung. Du lernst Verkaufsgrundlagen und den Umgang mit Kunden.",
            canton: "TG",
            city: "Winterthur",
            educationType: .eba,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 2,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Einstieg leicht gemacht, unterstützendes Team.",
            cultureTags: ["Einstieg", "Unterstützend", "Praxisnah"],
            requirements: ["Abgeschlossene Volksschule", "Freundliches Auftreten", "Pünktlichkeit"],
            compatibilityScore: 0.57,
            berufsschuleCanton: "TG",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Marktgasse 5, 8400 Winterthur",
            lat: 47.5001,
            lng: 8.7243,
            berufCategory: "detailhandel"
        ),

        // MARK: – Soziales (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Coop",
            companyLogoUrl: nil,
            berufCode: "94300",
            berufTitle: "Fachfrau/-mann Betreuung EFZ",
            title: "Fachfrau/-mann Betreuung EFZ Kinderbetreuung",
            description: "Begleite und fördere Kinder in ihrem Alltag. Du arbeitest in einer Kindertagesstätte und gestaltest ein anregendes Umfeld für die Kleinsten.",
            canton: "LU",
            city: "Luzern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Kinderfreundlich, herzlich und engagiert.",
            cultureTags: ["Kinderbetreuung", "Herzlich", "Sinnvoll"],
            requirements: ["Sek A oder B", "Freude an der Arbeit mit Kindern", "Geduld", "Verantwortungsbewusstsein"],
            compatibilityScore: 0.72,
            berufsschuleCanton: "LU",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Langensandstrasse 51, 6005 Luzern",
            lat: 47.0468,
            lng: 8.3115,
            berufCategory: "soziales"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Inselspital Bern",
            companyLogoUrl: nil,
            berufCode: "94300",
            berufTitle: "Fachfrau/-mann Betreuung EFZ",
            title: "Fachfrau/-mann Betreuung EFZ Behindertenbetreuung",
            description: "Unterstütze Menschen mit Beeinträchtigungen im Alltag und fördere ihre Selbstständigkeit. Eine sinnvolle und bereichernde Ausbildung.",
            canton: "BE",
            city: "Bern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Inklusion, Wertschätzung und individuelle Förderung.",
            cultureTags: ["Inklusion", "Sinnvoll", "Fördernd"],
            requirements: ["Sek B oder höher", "Empathie", "Geduld", "Belastbarkeit"],
            compatibilityScore: 0.70,
            berufsschuleCanton: "BE",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Murtenstrasse 50, 3008 Bern",
            lat: 46.9465,
            lng: 7.4230,
            berufCategory: "soziales"
        ),

        // MARK: – Handwerk (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Schreinerei Huber",
            companyLogoUrl: nil,
            berufCode: "51700",
            berufTitle: "Schreiner/in EFZ",
            title: "Schreiner/in EFZ Möbel/Innenausbau",
            description: "Arbeite mit Holz und erschaffe individuelle Möbel und Innenausbauten. Von der Skizze bis zum fertigen Produkt begleitest du jedes Projekt.",
            canton: "TG",
            city: "Winterthur",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Traditionelles Handwerk trifft moderne Technik.",
            cultureTags: ["Handwerk", "Kreativ", "Holz"],
            requirements: ["Sek B", "Handwerkliches Geschick", "Räumliches Vorstellungsvermögen"],
            compatibilityScore: 0.75,
            berufsschuleCanton: "TG",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Gewerbestrasse 8, 8500 Frauenfeld",
            lat: 47.5575,
            lng: 8.8987,
            berufCategory: "handwerk"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Metallbau Fischer AG",
            companyLogoUrl: nil,
            berufCode: "51700",
            berufTitle: "Schreiner/in EFZ",
            title: "Schreiner/in EFZ Bau/Fenster",
            description: "Spezialisiere dich auf den Bau von Fenstern, Türen und Fassadenelementen. Du lernst präzises Arbeiten mit modernen Maschinen und CNC-Technik.",
            canton: "SO",
            city: "Olten",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Qualität, Zuverlässigkeit und Teamarbeit.",
            cultureTags: ["Qualität", "Präzision", "Teamwork"],
            requirements: ["Sek B", "Technisches Verständnis", "Sorgfalt"],
            compatibilityScore: 0.68,
            berufsschuleCanton: "SO",
            companySize: .medium,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Tannwaldstrasse 88, 4600 Olten",
            lat: 47.3522,
            lng: 7.9068,
            berufCategory: "handwerk"
        ),

        // MARK: – Logistik (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Post CH AG",
            companyLogoUrl: nil,
            berufCode: "95600",
            berufTitle: "Logistiker/in EFZ",
            title: "Logistiker/in EFZ Distribution",
            description: "Sorge dafür, dass Pakete und Briefe pünktlich ankommen. Du lernst Logistikprozesse, Lagerbewirtschaftung und den Umgang mit moderner Technik.",
            canton: "ZH",
            city: "Zürich",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Effizienz, Bewegung und Verantwortung.",
            cultureTags: ["Bewegung", "Verantwortung", "Logistik"],
            requirements: ["Sek B", "Körperliche Fitness", "Organisationsfähigkeit"],
            compatibilityScore: 0.65,
            berufsschuleCanton: "ZH",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Mülligen, 8021 Zürich",
            lat: 47.4115,
            lng: 8.5048,
            berufCategory: "logistik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "SBB",
            companyLogoUrl: nil,
            berufCode: "95600",
            berufTitle: "Logistiker/in EBA",
            title: "Logistiker/in EBA",
            description: "Steige mit einer zweijährigen Ausbildung in die Welt der Logistik ein. Du lernst Waren entgegenzunehmen, zu lagern und für den Versand vorzubereiten.",
            canton: "SO",
            city: "Olten",
            educationType: .eba,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 2,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Strukturiertes Arbeiten, gute Betreuung und viel Bewegung.",
            cultureTags: ["Einstieg", "Bewegung", "Strukturiert"],
            requirements: ["Abgeschlossene Volksschule", "Körperliche Belastbarkeit", "Zuverlässigkeit"],
            compatibilityScore: 0.55,
            berufsschuleCanton: "SO",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Bahnhofquai 12, 4600 Olten",
            lat: 47.3516,
            lng: 7.9074,
            berufCategory: "logistik"
        ),

        // MARK: – Bau (3 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Autogarage Keller",
            companyLogoUrl: nil,
            berufCode: "33200",
            berufTitle: "Maurer/in EFZ",
            title: "Maurer/in EFZ",
            description: "Baue Häuser, Brücken und Gebäude. Du lernst Mauern, Betonieren und Isolieren auf verschiedenen Baustellen in der Region.",
            canton: "AG",
            city: "Aarau",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Draussen arbeiten, im Team anpacken und etwas Bleibendes schaffen.",
            cultureTags: ["Outdoor", "Teamwork", "Körperlich"],
            requirements: ["Sek B", "Körperliche Fitness", "Handwerkliches Geschick"],
            compatibilityScore: 0.61,
            berufsschuleCanton: "AG",
            companySize: .medium,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Rohrerstrasse 18, 5000 Aarau",
            lat: 47.3900,
            lng: 8.0520,
            berufCategory: "bau"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "ABB Schweiz",
            companyLogoUrl: nil,
            berufCode: "34500",
            berufTitle: "Zeichner/in EFZ",
            title: "Zeichner/in EFZ Fachrichtung Architektur",
            description: "Erstelle Pläne und 3D-Modelle für Bauprojekte. Du arbeitest mit CAD-Software und begleitest Projekte von der Idee bis zur Realisierung.",
            canton: "AG",
            city: "Baden",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Präzision, Planung und kreative Lösungen.",
            cultureTags: ["Planung", "CAD", "Kreativ"],
            requirements: ["Sek A", "Räumliches Vorstellungsvermögen", "Sorgfalt", "Interesse an Architektur"],
            compatibilityScore: 0.79,
            berufsschuleCanton: "AG",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Segelhofstrasse 2, 5405 Baden-Dättwil",
            lat: 47.4571,
            lng: 8.2941,
            berufCategory: "bau"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Metallbau Fischer AG",
            companyLogoUrl: nil,
            berufCode: "33200",
            berufTitle: "Maurer/in EFZ",
            title: "Maurer/in EFZ Hochbau",
            description: "Errichte Wohn- und Geschäftshäuser und lerne alle Bereiche des Hochbaus kennen. Abwechslungsreiche Baustellen warten auf dich.",
            canton: "LU",
            city: "Luzern",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Solides Handwerk, guter Zusammenhalt und vielfältige Projekte.",
            cultureTags: ["Baustelle", "Teamwork", "Vielfältig"],
            requirements: ["Sek B", "Körperliche Fitness", "Teamfähigkeit"],
            compatibilityScore: 0.58,
            berufsschuleCanton: "LU",
            companySize: .medium,
            isVerified: false,
            isPremium: false,
            workplaceAddress: "Allmendstrasse 30, 6005 Luzern",
            lat: 47.0455,
            lng: 8.3140,
            berufCategory: "bau"
        ),

        // MARK: – Natur (2 entries)

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Garten & Landschaft Brunner",
            companyLogoUrl: nil,
            berufCode: "17000",
            berufTitle: "Gärtner/in EFZ",
            title: "Gärtner/in EFZ Garten- und Landschaftsbau",
            description: "Gestalte Gärten, Parks und Aussenanlagen. Du arbeitest draussen, pflanzt, pflegst und baust individuelle Grünanlagen für unsere Kunden.",
            canton: "GR",
            city: "Chur",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Naturverbundenheit, frische Luft und kreative Gartengestaltung.",
            cultureTags: ["Natur", "Outdoor", "Kreativ"],
            requirements: ["Sek B", "Freude an der Natur", "Körperliche Fitness", "Wetterfestigkeit"],
            compatibilityScore: 0.64,
            berufsschuleCanton: "GR",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Ringstrasse 55, 7000 Chur",
            lat: 46.8520,
            lng: 9.5270,
            berufCategory: "natur"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Migros",
            companyLogoUrl: nil,
            berufCode: "17000",
            berufTitle: "Gärtner/in EBA",
            title: "Gärtner/in EBA Pflanzenproduktion",
            description: "Steige mit einer zweijährigen Ausbildung in die grüne Branche ein. Du lernst Pflanzen zu vermehren, zu pflegen und für den Verkauf vorzubereiten.",
            canton: "VD",
            city: "Lausanne",
            educationType: .eba,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 2,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Einstieg in die Pflanzenwelt mit guter Betreuung.",
            cultureTags: ["Pflanzen", "Einstieg", "Natur"],
            requirements: ["Abgeschlossene Volksschule", "Freude an Pflanzen", "Sorgfalt"],
            compatibilityScore: 0.56,
            berufsschuleCanton: "VD",
            companySize: .large,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Chemin de Mornex 1, 1003 Lausanne",
            lat: 46.5197,
            lng: 6.6323,
            berufCategory: "natur"
        ),

        // MARK: – Additional variety entries

        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Roche",
            companyLogoUrl: nil,
            berufCode: "88611",
            berufTitle: "Informatiker/in EFZ",
            title: "Informatiker/in EFZ Applikationsentwicklung",
            description: "Entwickle Software für die pharmazeutische Industrie. Du arbeitest an spannenden Projekten, die einen Beitrag zur Gesundheit leisten.",
            canton: "BS",
            city: "Basel",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Innovation in der Pharmabranche, internationales Umfeld.",
            cultureTags: ["Pharma", "Innovation", "International"],
            requirements: ["Sek A", "Gute Noten in Mathe und Naturwissenschaften", "Englischkenntnisse"],
            compatibilityScore: 0.89,
            berufsschuleCanton: "BS",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Grenzacherstrasse 124, 4058 Basel",
            lat: 47.5628,
            lng: 7.5943,
            berufCategory: "informatik"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Novartis",
            companyLogoUrl: nil,
            berufCode: "68500",
            berufTitle: "Kauffrau/-mann EFZ",
            title: "Kauffrau/-mann EFZ Pharmabranche",
            description: "Erhalte Einblicke in die kaufmännische Seite eines globalen Pharmaunternehmens. Du durchläufst verschiedene Abteilungen und arbeitest international.",
            canton: "BS",
            city: "Basel",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 3,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Wissenschaft trifft Business, global vernetzt.",
            cultureTags: ["International", "Wissenschaft", "Karrierechancen"],
            requirements: ["Sek A", "Gute Fremdsprachenkenntnisse", "Interesse an Gesundheit"],
            compatibilityScore: 0.83,
            berufsschuleCanton: "BS",
            companySize: .large,
            isVerified: true,
            isPremium: true,
            workplaceAddress: "Lichtstrasse 35, 4056 Basel",
            lat: 47.5670,
            lng: 7.5800,
            berufCategory: "kaufmännisch"
        ),
        LehrstelleCard(
            id: UUID(),
            companyId: UUID(),
            companyName: "Autogarage Keller",
            companyLogoUrl: nil,
            berufCode: "45700",
            berufTitle: "Polymechaniker/in EFZ",
            title: "Automobil-Mechatroniker/in EFZ",
            description: "Diagnostiziere und repariere moderne Fahrzeuge. Du lernst Mechanik, Elektronik und Computertechnik in einem gut ausgestatteten Betrieb.",
            canton: "SG",
            city: "St. Gallen",
            educationType: .efz,
            startDate: Calendar.current.date(from: DateComponents(year: 2027, month: 8, day: 1)),
            durationYears: 4,
            videoUrl: nil,
            photoUrls: [],
            cultureDescription: "Technikbegeisterung, Sorgfalt und ein eingespieltes Team.",
            cultureTags: ["Autos", "Technik", "Praxisnah"],
            requirements: ["Sek A oder B", "Technisches Verständnis", "Handwerkliches Geschick"],
            compatibilityScore: 0.76,
            berufsschuleCanton: "SG",
            companySize: .small,
            isVerified: true,
            isPremium: false,
            workplaceAddress: "Zürcher Strasse 204, 9014 St. Gallen",
            lat: 47.4190,
            lng: 9.3850,
            berufCategory: "technik"
        ),
    ]
}
