-- =============================================================================
-- Migration: Update berufe with O*NET 30.1 RIASEC scores
-- Generated by scripts/onet_import.py
-- Source: https://www.onetcenter.org/database.html (O*NET 30.1)
-- =============================================================================

-- Add new columns for Holland code and O*NET SOC cross-reference
ALTER TABLE berufe ADD COLUMN IF NOT EXISTS holland_code TEXT;
ALTER TABLE berufe ADD COLUMN IF NOT EXISTS onet_soc_code TEXT;

-- =============================================================================
-- Directly-mapped berufe (Swiss code -> O*NET SOC)
-- =============================================================================
UPDATE berufe SET
    personality_fit = '{"realistic": 0.69, "investigative": 0.29, "artistic": 0.01, "social": 0.27, "enterprising": 0.76, "conventional": 0.58}',
    holland_code = 'ERC',
    onet_soc_code = '11-9013.00'
WHERE code = '15000';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.1, "artistic": 0.15, "social": 0.07, "enterprising": 0.13, "conventional": 0.39}',
    holland_code = 'RCA',
    onet_soc_code = '37-3011.00'
WHERE code = '17000';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.9, "investigative": 0.11, "artistic": 0.2, "social": 0.12, "enterprising": 0.18, "conventional": 0.57}',
    holland_code = 'RCA',
    onet_soc_code = '51-3011.00'
WHERE code = '21104';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.97, "investigative": 0.18, "artistic": 0.11, "social": 0.03, "enterprising": 0.04, "conventional": 0.49}',
    holland_code = 'RCI',
    onet_soc_code = '47-2021.00'
WHERE code = '33200';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.74, "investigative": 0.54, "artistic": 0.58, "social": 0.09, "enterprising": 0.09, "conventional": 0.65}',
    holland_code = 'RCA',
    onet_soc_code = '17-3011.00'
WHERE code = '34500';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.45, "artistic": 0.15, "social": 0.03, "enterprising": 0.04, "conventional": 0.57}',
    holland_code = 'RCI',
    onet_soc_code = '51-4041.00'
WHERE code = '45700';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.45, "artistic": 0.15, "social": 0.03, "enterprising": 0.04, "conventional": 0.57}',
    holland_code = 'RCI',
    onet_soc_code = '51-4041.00'
WHERE code = '45800';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.28, "artistic": 0.05, "social": 0.04, "enterprising": 0.14, "conventional": 0.54}',
    holland_code = 'RCI',
    onet_soc_code = '47-2111.00'
WHERE code = '46500';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.56, "artistic": 0.06, "social": 0.0, "enterprising": 0.0, "conventional": 0.6}',
    holland_code = 'RCI',
    onet_soc_code = '17-3024.00'
WHERE code = '47600';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.96, "investigative": 0.15, "artistic": 0.2, "social": 0.15, "enterprising": 0.13, "conventional": 0.41}',
    holland_code = 'RCA',
    onet_soc_code = '47-2031.00'
WHERE code = '51200';

UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.18, "artistic": 0.24, "social": 0.02, "enterprising": 0.03, "conventional": 0.43}',
    holland_code = 'RCA',
    onet_soc_code = '51-7011.00'
WHERE code = '51700';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.37, "investigative": 0.3, "artistic": 1.0, "social": 0.22, "enterprising": 0.43, "conventional": 0.46}',
    holland_code = 'ACE',
    onet_soc_code = '27-1024.00'
WHERE code = '64700';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.26, "investigative": 0.65, "artistic": 0.58, "social": 0.2, "enterprising": 0.36, "conventional": 0.56}',
    holland_code = 'IAC',
    onet_soc_code = '15-1255.00'
WHERE code = '64800';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.16, "investigative": 0.06, "artistic": 0.0, "social": 0.44, "enterprising": 0.53, "conventional": 0.99}',
    holland_code = 'CES',
    onet_soc_code = '43-6014.00'
WHERE code = '68500';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.32, "investigative": 0.14, "artistic": 0.0, "social": 0.34, "enterprising": 0.36, "conventional": 0.97}',
    holland_code = 'CES',
    onet_soc_code = '43-9061.00'
WHERE code = '68600';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.38, "investigative": 0.0, "artistic": 0.18, "social": 0.33, "enterprising": 0.85, "conventional": 0.67}',
    holland_code = 'ECR',
    onet_soc_code = '41-2031.00'
WHERE code = '71300';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.38, "investigative": 0.0, "artistic": 0.18, "social": 0.33, "enterprising": 0.85, "conventional": 0.67}',
    holland_code = 'ECR',
    onet_soc_code = '41-2031.00'
WHERE code = '71400';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.8, "investigative": 0.07, "artistic": 0.24, "social": 0.3, "enterprising": 0.47, "conventional": 0.54}',
    holland_code = 'RCE',
    onet_soc_code = '35-2014.00'
WHERE code = '79000';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.51, "investigative": 0.0, "artistic": 0.15, "social": 0.64, "enterprising": 0.53, "conventional": 0.59}',
    holland_code = 'SCE',
    onet_soc_code = '35-3031.00'
WHERE code = '79100';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.6, "investigative": 0.29, "artistic": 0.0, "social": 0.79, "enterprising": 0.13, "conventional": 0.54}',
    holland_code = 'SRC',
    onet_soc_code = '31-1131.00'
WHERE code = '86914';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.6, "investigative": 0.29, "artistic": 0.0, "social": 0.79, "enterprising": 0.13, "conventional": 0.54}',
    holland_code = 'SRC',
    onet_soc_code = '31-1131.00'
WHERE code = '86916';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.51, "investigative": 0.47, "artistic": 0.0, "social": 0.63, "enterprising": 0.16, "conventional": 0.79}',
    holland_code = 'CSR',
    onet_soc_code = '31-9092.00'
WHERE code = '86930';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.49, "investigative": 0.81, "artistic": 0.21, "social": 0.15, "enterprising": 0.15, "conventional": 0.74}',
    holland_code = 'ICR',
    onet_soc_code = '15-1252.00'
WHERE code = '88611';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.53, "investigative": 0.51, "artistic": 0.0, "social": 0.2, "enterprising": 0.41, "conventional": 0.86}',
    holland_code = 'CRI',
    onet_soc_code = '15-1244.00'
WHERE code = '88612';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.26, "investigative": 0.65, "artistic": 0.58, "social": 0.2, "enterprising": 0.36, "conventional": 0.56}',
    holland_code = 'IAC',
    onet_soc_code = '15-1255.00'
WHERE code = '88613';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.51, "investigative": 0.48, "artistic": 0.0, "social": 0.39, "enterprising": 0.22, "conventional": 0.81}',
    holland_code = 'CRI',
    onet_soc_code = '15-1232.00'
WHERE code = '88900';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.39, "investigative": 0.05, "artistic": 0.42, "social": 0.82, "enterprising": 0.32, "conventional": 0.43}',
    holland_code = 'SCA',
    onet_soc_code = '39-9011.00'
WHERE code = '94300';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.85, "investigative": 0.0, "artistic": 0.0, "social": 0.07, "enterprising": 0.14, "conventional": 0.6}',
    holland_code = 'RCE',
    onet_soc_code = '53-7062.00'
WHERE code = '95600';

UPDATE berufe SET
    personality_fit = '{"realistic": 0.85, "investigative": 0.0, "artistic": 0.0, "social": 0.07, "enterprising": 0.14, "conventional": 0.6}',
    holland_code = 'RCE',
    onet_soc_code = '53-7062.00'
WHERE code = '95700';

-- =============================================================================
-- Field-based averages for berufe NOT in the direct mapping
-- These use averaged RIASEC scores from mapped berufe in the same field.
-- =============================================================================
-- Field: Bau (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.85, "investigative": 0.36, "artistic": 0.34, "social": 0.06, "enterprising": 0.07, "conventional": 0.57}',
    holland_code = 'RCI'
WHERE field = 'Bau'
  AND code NOT IN ('33200', '34500')
  AND holland_code IS NULL;

-- Field: Design (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.32, "investigative": 0.47, "artistic": 0.79, "social": 0.21, "enterprising": 0.4, "conventional": 0.51}',
    holland_code = 'ACI'
WHERE field = 'Design'
  AND code NOT IN ('64700', '64800')
  AND holland_code IS NULL;

-- Field: Detailhandel (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.38, "investigative": 0.0, "artistic": 0.18, "social": 0.33, "enterprising": 0.85, "conventional": 0.67}',
    holland_code = 'ECR'
WHERE field = 'Detailhandel'
  AND code NOT IN ('71300', '71400')
  AND holland_code IS NULL;

-- Field: Gastronomie (average RIASEC from 3 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.74, "investigative": 0.06, "artistic": 0.2, "social": 0.35, "enterprising": 0.39, "conventional": 0.57}',
    holland_code = 'RCE'
WHERE field = 'Gastronomie'
  AND code NOT IN ('21104', '79000', '79100')
  AND holland_code IS NULL;

-- Field: Gesundheit (average RIASEC from 3 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.57, "investigative": 0.35, "artistic": 0.0, "social": 0.74, "enterprising": 0.14, "conventional": 0.62}',
    holland_code = 'SCR'
WHERE field = 'Gesundheit'
  AND code NOT IN ('86914', '86916', '86930')
  AND holland_code IS NULL;

-- Field: Handwerk (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.98, "investigative": 0.16, "artistic": 0.22, "social": 0.08, "enterprising": 0.08, "conventional": 0.42}',
    holland_code = 'RCA'
WHERE field = 'Handwerk'
  AND code NOT IN ('51200', '51700')
  AND holland_code IS NULL;

-- Field: Informatik (average RIASEC from 4 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.45, "investigative": 0.61, "artistic": 0.2, "social": 0.23, "enterprising": 0.28, "conventional": 0.74}',
    holland_code = 'CIR'
WHERE field = 'Informatik'
  AND code NOT IN ('88611', '88612', '88613', '88900')
  AND holland_code IS NULL;

-- Field: Kaufmännisch (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.24, "investigative": 0.1, "artistic": 0.0, "social": 0.39, "enterprising": 0.45, "conventional": 0.98}',
    holland_code = 'CES'
WHERE field = 'Kaufmännisch'
  AND code NOT IN ('68500', '68600')
  AND holland_code IS NULL;

-- Field: Logistik (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.85, "investigative": 0.0, "artistic": 0.0, "social": 0.07, "enterprising": 0.14, "conventional": 0.6}',
    holland_code = 'RCE'
WHERE field = 'Logistik'
  AND code NOT IN ('95600', '95700')
  AND holland_code IS NULL;

-- Field: Natur (average RIASEC from 2 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.84, "investigative": 0.2, "artistic": 0.08, "social": 0.17, "enterprising": 0.45, "conventional": 0.48}',
    holland_code = 'RCE'
WHERE field = 'Natur'
  AND code NOT IN ('15000', '17000')
  AND holland_code IS NULL;

-- Field: Soziales (average RIASEC from 1 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 0.39, "investigative": 0.05, "artistic": 0.42, "social": 0.82, "enterprising": 0.32, "conventional": 0.43}',
    holland_code = 'SCA'
WHERE field = 'Soziales'
  AND code NOT IN ('94300')
  AND holland_code IS NULL;

-- Field: Technik (average RIASEC from 4 mapped berufe)
UPDATE berufe SET
    personality_fit = '{"realistic": 1.0, "investigative": 0.43, "artistic": 0.1, "social": 0.03, "enterprising": 0.06, "conventional": 0.57}',
    holland_code = 'RCI'
WHERE field = 'Technik'
  AND code NOT IN ('45700', '45800', '46500', '47600')
  AND holland_code IS NULL;

